### ISSUE TITLE
Colours look monochrome starting at version 7.0.0

### ISSUE THREAD

**Issue by jeffman** [jonathanfilip/vim-lucius#6]
I'm trying to use Lucius on a Linux session that I'm SSH-ing into via putty from Windows. Putty is using `xterm-256color` and "Allow terminal to use xterm 256-colour mode" is set. My .vimrc file looks like this:

```
set number
set t_Co=256
colorscheme lucius
LuciusDark
```

Version 6.1.0 of Lucius looks like this for me:

![](http://i.imgur.com/iNiupuo.png)

Version 7.0.0 looks like this:

![](http://i.imgur.com/1cHKR37.png)

**Comment by jonathanfilip** [comment]
What version of Vim are you using?

Also, any reason you aren't using the newest version? It's been a while since I've looked at those older versions.

**Comment by jeffman** [comment]
I'm using version 7.0 of Vim. Lucius v7.0.0 is the version where I start observing this issue, but it persists up to and including the latest one (I cloned the current version on Github and the issue still occurs).

**Comment by jonathanfilip** [comment]
I've never tested the colorscheme on anything less than 7.2 (and that was an old version of the scheme), so I'm not sure what if there is some syntax or settings I use that don't work. It is very strange that none of the colors seem to be set in your second screenshot. Is there anything unusual in :messages? If you try :LuciusDark after you have started up, does anything happen? You can also try :let g:lucius_style="dark" and then :colorscheme lucius (even set background=dark before that too). Let me know if any of that works or has an interesting effect.

**Comment by jeffman** [comment]
Using Vim 7.4.640 with the latest version of Lucius, I get this now:

![](http://i.imgur.com/TcPJTv1.png)

:messages doesn't have anything relevant; :LuciusDark doesn't change anything after startup; the other commands don't change anything either.

**Comment by jonathanfilip** [comment]
What does ":echo &ft" say when you are in that file? Also make sure ":syntax on" is set. It looks like the colors are set now, based on your latest screenshot, but syntax highlighting isn't on. Try ":set ft=cpp" or ":set ft=c" too just to see if that has any effect. Let me know if any of those work or provide any insight.

**Comment by jeffman** [comment]
syntax on was the issue, thanks! Works fine now.
