### ISSUE TITLE
htmlTag under cursor has no background color

### ISSUE THREAD

**Issue by pmcode** [jonathanfilip/vim-lucius#7]
![lucius2](https://cloud.githubusercontent.com/assets/7430017/6235990/29baae02-b700-11e4-96dc-0ea39c6bd777.png)
Can you please add proper highlight for the htmlTag under cursor? At this time it can be easy to confuse the position of the cursor.

**Comment by jonathanfilip** [comment]
The html syntax file already links these to colors defined in the color scheme:

  HtmlHiLink htmlTag                     Function
  HtmlHiLink htmlEndTag                  Identifier
  HtmlHiLink htmlArg                     Type
  HtmlHiLink htmlTagName                 htmlStatement
  HtmlHiLink htmlSpecialTagName          Exception
  HtmlHiLink htmlValue                     String
  HtmlHiLink htmlSpecialChar             Special

I'm not sure why Vim is behaving that way. When I have Vim running in Putty, my cursor is normal, but I don't get a matching highlight in html. I get one matching in other filetypes, however (python with parenthesis).

When I run it in iTerm2, I see my cursor just fine and the matching character highlights using the MatchParen definition. It also highlights just fine in python.

I think one of my coworkers experienced a similar problem, so I will ask them about it when I have a chance.

Are you able to try it in something other than Konsole to see if that produces anything different?

**Comment by pmcode** [comment]
Seems like one more Konsole bug. 
https://github.com/morhetz/gruvbox/issues/35
I have tried urxvt and all works well.
Thanks, **jonathanfilip**.
