### ISSUE TITLE
Colors not as bright on PuTTY?

### ISSUE THREAD

**Issue by adam-beck** [jonathanfilip/vim-lucius#8]
I am using the `vim-lucius` colorscheme on two of my machines. One is a regular linux box and the other I SSH into a VM with PuTTY. The colorscheme looks great on my linux box but the colors seem *ever so slightly off* on my PuTTY window. 

So this is just a question: does anybody else notice the slight color differences. For instance, the `function` has a very pronounced blue on my linux machine but you almost have to squint to see it in PuTTY. 

I am using the same exact `.tmux.conf` and `.vimrc`. I also have the same color palette applied to both terminals, although, that shouldn't make a difference.

Another strange this that in my `.vimrc` I have the lines:
```
syntax on
color lucius
```

Yet, once I'm inside vim and change to LuciusLight my GitGutter changes. I cannot seem to get back to my original colors; even if I cycle all the options.

I'm sure this is a PuTTY thing but thought I'd ask.

**Comment by jonathanfilip** [comment]
I think it's just a mix of font/OS/program. I have the same font and colors set up on iTerm on OS X and on PuTTY on Windows 7 and the iTerm session's colors are much more vibrant. The font rendering is also slightly different, even though I'm using Consolas on both.

As for your second problem... I'm not sure. What if you replace "color lucius" with LuciusLight in your .vimrc? Are you able to provide screenshots of what it looks like before and after?

**Comment by adam-beck** [comment]
The GitGutter problem is not that big of a deal. I make some customizations to it so I'm sure that is the reasoning but I mentioned it in case anybody else was seeing it. I'm glad to know I can stop trying to perfect my colorscheme if you have also noticed that the font/OS/program changes the colorscheme slightly. I might tweak it so that PuTTY at least attempts to show the original colors.

Awesome colorscheme though! I'm sing it everywhere.

**Comment by jonathanfilip** [comment]
One other test you could try is compare the PuTTY one to gVim on Windows. They look the same for me, so it really is more of an OS font rendering thing. If your PuTTY one is different, then we might have something else going on.

**Comment by adam-beck** [comment]
I will try that but I will be away for the weekend. I even went so far last night as drastically changing the settings physically on my monitor just hoping for a fix. Nothing. It is nothing to be too concerned about but I have fought VIm with colorschemes before and I am not about to let it win.
